### ISSUE TITLE
APK Demo

### ISSUE THREAD

**Issue by sss26** [kennanmell/Handoff#12]
Once the APK has been downloaded/created (either by retrieving it from our user site or a developer actually compiling it) sometimes when you attempt to open it with Bluestacks it results in an error message. This usually stops after a couple attempts of opening, but may reoccur randomly.

**Comment by epeach** [comment]
Any updates on whether this has been resolved?

**Comment by epeach** [comment]
Chatted with Sam. This appears to be an issue with Bluestacks and not our app.

**Comment by kennanmell** [comment]
Ok then I'll close the issue.
