### ISSUE TITLE
Edit Request Modal doesn't interact with back button on phone

### ISSUE THREAD

**Issue by epeach** [kennanmell/Handoff#13]
The Edit Request Modal in the placeholder for Edit Request, doesn't respond to the back button on the phone. This might be good as it ensures that the client has to complete their interaction with this modal and doesn't allow them to erroneously quit it. Alternatively, users might find this frustrating. Let's make exit buttons really clear and ask for input during user tests.

**Comment by kennanmell** [comment]
I think we have pop-ups when the user presses the back button now, just telling them to use the close button. But still not a great solution so we should probably leave this open.

**Comment by kennanmell** [comment]
At this point, I think we're best off just leaving the current fix in, in order to avoid accidentally introducing new, more serious bugs. Closing.
