### ISSUE TITLE
Edit Profile Issue

### ISSUE THREAD

**Issue by sss26** [kennanmell/Handoff#24]
When editing an organization profile, any edits made will not be seen in the application until the organization logs out and logs back in. If you try to edit the profile several separate times, only the last edit will be saved once you log out.

**Comment by Ianhadden** [comment]
Edits will now be saved locally. The part about only the last edit being saved doesn't make sense to me, because every time you edit, the changes are pushed to the back end. I'd like some clarification one what is meant by that

**Comment by kennanmell** [comment]
Just tested this and it looks fixed to me. Closing.
